import type { DevotionalDay, WhatsAppGroup, HistoryEntry, PdfFile } from './app-store'

export const TODAY = 23

export const SEED_DAYS: DevotionalDay[] = [
  { d: 1, title: 'Awakening of the Watchman', ref: 'Ezekiel 33:6', verse: 'But if the watchman see the sword come, and blow not the trumpet, and the people be not warned…', body: ['Every generation receives a charge. Some carry their charge quietly; others lift it as a banner. The watchman in Ezekiel was given neither sword nor armor — only a trumpet, and the courage to sound it on time.', 'Today, listen for what God is whispering to your generation. The trumpet you carry may sound small in your own ears, but heaven does not measure by volume. It measures by obedience.'], prayer: ['Lord, awaken in me the discipline to listen before I speak.', 'Help me to sound the warning You place in my heart without fear of crowds.', 'Make me a faithful watchman in my home, my school, my circle.'], resolve: 'I will not silence what God has asked me to sound.', status: 'sent' },
  { d: 2, title: 'The Cost of a Clean Heart', ref: 'Psalm 51:10', verse: 'Create in me a clean heart, O God; and renew a right spirit within me.', body: ['David did not ask for a comfortable heart. He asked for a clean one. A clean heart costs something — it costs the right to nurse a grudge, to rehearse an offense, to play victim of a story we have already been delivered from.', 'Renewal begins in the small choice to stop polishing what God has asked you to surrender.'], prayer: ['Search me, O God, in places I have stopped checking.', 'Wash from me the residue of yesterday\'s arguments.', 'Renew a steady spirit when I am tempted to react.'], resolve: 'I will trade my comfortable heart for a clean one.', status: 'sent' },
  { d: 3, title: 'When the Cloud Moves', ref: 'Numbers 9:17', verse: 'Whenever the cloud was taken up from over the tabernacle, then after that the children of Israel journeyed.', body: ['Israel did not move when it was convenient. They moved when the cloud moved. Sometimes the cloud lingered, and they unpacked their lives in a place they had hoped to leave. Sometimes the cloud lifted at midnight, and they marched in the dark.', 'God is not careless with our pacing. He is teaching us to follow, not to forecast.'], prayer: ['Teach me to wait without complaining and to move without delay.', 'Anchor my plans to Your presence, not to my schedule.', 'Let my obedience be quicker than my opinion.'], resolve: 'I will move when the cloud moves, and not before.', status: 'sent' },
  { d: 4, title: 'The Quiet Authority of Yes', ref: 'Luke 1:38', verse: 'Behold the handmaid of the Lord; be it unto me according to thy word.', body: ['Mary\'s yes did not arrive with a press conference. It was whispered in a small room with no audience but heaven. And yet that yes carried the weight of every prophecy ever spoken about the Messiah.', 'A teenage girl\'s obedience reshaped history. Your yes is not small either.'], prayer: ['Give me the courage to say yes before I understand the full cost.', 'Quiet the voices that ask me to weigh my reputation first.', 'Let my yes carry the weight of trust, not the weight of fear.'], resolve: 'I will say yes in the quiet, and trust God with the noise.', status: 'sent' },
  { d: 5, title: 'Bread for the Journey', ref: '1 Kings 19:7', verse: 'Arise and eat; because the journey is too great for thee.', body: ['Elijah was under a tree, asking to die. The angel did not lecture him. The angel fed him. Twice.', 'Sometimes the most spiritual thing you can do is eat, rest, and let God set the pace. Strength is not a sermon you preach to yourself — it is bread you receive.'], prayer: ['Teach me to receive care without earning it.', 'Send the bread I cannot bake for myself.', 'Strengthen me for the next forty days, not the next forty years.'], resolve: 'I will accept the bread God sends, even when I think I should be fasting.', status: 'sent' },
  { d: 6, title: 'Stones for the Sling', ref: '1 Samuel 17:40', verse: 'And he chose him five smooth stones out of the brook.', body: ['David did not pick up Saul\'s armor. He picked up what the brook had already shaped. The stones were smoothed by years of water he never saw running.', 'God has been smoothing things in your life you do not even remember. Today, He invites you to use them.'], prayer: ['Help me to recognize the stones You have already prepared for me.', 'Free me from borrowed armor that does not fit my calling.', 'Steady my aim when the giant is louder than my faith.'], resolve: 'I will fight with what God has shaped, not what others have lent me.', status: 'sent' },
  { d: 7, title: 'A Sabbath That Sees', ref: 'Mark 2:27', verse: 'The sabbath was made for man, and not man for the sabbath.', body: ['Rest is not a reward for finishing. It is a rhythm for becoming. The God who never sleeps still insisted that we should.', 'A Sabbath that sees is one where you actually look — at your family, at the sky, at the work of your own hands. Look long enough to be grateful.'], prayer: ['Slow me down enough to see what I have been running past.', 'Free me from the lie that my worth lives in my output.', 'Teach my soul to rest without guilt.'], resolve: 'I will rest like someone who trusts the One who never sleeps.', status: 'sent' },
  { d: 8, title: 'The Long Walk Home', ref: 'Luke 15:20', verse: 'And he arose, and came to his father. But when he was yet a great way off, his father saw him…', body: ['The prodigal rehearsed his speech the whole way home. He never got to finish it. The father interrupted with a robe, a ring, and a feast.', 'God is not waiting at the gate to grade your apology. He is running toward you with what you lost.'], prayer: ['Father, run toward me where I have stopped running toward myself.', 'Quiet the speech I have been rehearsing in shame.', 'Restore the ring of identity I gave away cheaply.'], resolve: 'I will let the Father interrupt my apology with His embrace.', status: 'sent' },
  { d: 9, title: 'Whispers in the Wind', ref: '1 Kings 19:12', verse: 'And after the fire a still small voice.', body: ['Elijah expected God in the earthquake. God came in the whisper. The loudest moments in your week may not be the holiest.', 'Make room for the still small voice. It speaks in the spaces between notifications.'], prayer: ['Lower the volume of my distractions.', 'Sharpen my ears for the whisper I keep missing.', 'Let me be a person who hears before they hurry.'], resolve: 'I will turn down the noise so I can turn up to the voice.', status: 'sent' },
  { d: 10, title: 'Mothers of Faith', ref: '2 Timothy 1:5', verse: 'The unfeigned faith that is in thee, which dwelt first in thy grandmother Lois, and thy mother Eunice.', body: ['Faith is often inherited before it is chosen. Today, honor the women whose prayers laid the foundation of yours — named or unnamed, present or departed.', 'And if you did not inherit faith, you can begin a line. Someone will one day call you the Lois of their story.'], prayer: ['Thank You for the prayers that reached me before I knew to pray.', 'Make my faith real enough to inherit.', 'Bless every mother of faith standing in the gap for someone today.'], resolve: 'I will live a faith worth handing down.', status: 'sent' },
  { d: 11, title: 'The Weight of Words', ref: 'Proverbs 18:21', verse: 'Death and life are in the power of the tongue.', body: ['Words frame worlds. The same mouth can bury a friend or raise a brother. Before you speak today, ask which world your words are building.', 'Silence, when chosen well, is also a sentence God can use.'], prayer: ['Set a guard before my mouth, and a wisdom behind my pause.', 'Help me to build with my words, not just to win with them.', 'Let what I say sound like the One who spoke me into being.'], resolve: 'I will speak life, or I will speak later.', status: 'sent' },
  { d: 12, title: 'Mended Nets', ref: 'Matthew 4:21', verse: 'In a ship with Zebedee their father, mending their nets.', body: ['Jesus did not call the disciples while they were fishing. He called them while they were mending. Repair work is holy work. Tending what is torn — friendships, faith, focus — qualifies you for what is next.', 'Stay faithful in the mending. The Master walks past nets that are being repaired.'], prayer: ['Give me patience for the slow work of mending.', 'Help me to repair before I replace.', 'Find me faithful in the small loop of restoration.'], resolve: 'I will mend what I am tempted to discard.', status: 'sent' },
  { d: 13, title: 'The Gate Called Beautiful', ref: 'Acts 3:6', verse: 'Silver and gold have I none; but such as I have give I thee.', body: ['Peter did not have what the beggar asked for. He had something better. Stop apologizing for not carrying what the world expects from you.', 'Give what you have. Heaven multiplies what is offered, not what is hoarded.'], prayer: ['Free me from the shame of empty pockets.', 'Show me the gift I keep underestimating in my hand.', 'Let what I have, given in faith, become what they actually needed.'], resolve: 'I will offer what I have, and trust God for the rest.', status: 'sent' },
  { d: 14, title: 'Burning But Not Consumed', ref: 'Exodus 3:3', verse: 'I will now turn aside, and see this great sight, why the bush is not burnt.', body: ['Moses turned aside. That single decision — to look longer than was convenient — is what placed him in conversation with God.', 'There are bushes burning in your week. Stop scrolling. Turn aside. Look.'], prayer: ['Slow me down at the burning bushes I have been walking past.', 'Make me curious about Your presence in ordinary places.', 'Speak my name where I have only heard my schedule.'], resolve: 'I will turn aside when something holy interrupts my ordinary.', status: 'sent' },
  { d: 15, title: 'The Half-Month Pause', ref: 'Lamentations 3:23', verse: 'They are new every morning: great is thy faithfulness.', body: ['You are at the middle of the month. Look back without flinching, and forward without panicking. The mercies that carried you to today are not on a budget.', 'God is not running out of grace at the halfway mark.'], prayer: ['Thank You for mercies I did not notice and did not deserve.', 'Renew me for the second half of this month.', 'Anchor me in the faithfulness that does not flinch.'], resolve: 'I will receive new mercies without rationing them.', status: 'sent' },
  { d: 16, title: 'A House on Rock', ref: 'Matthew 7:24', verse: 'Whosoever heareth these sayings of mine, and doeth them, I will liken him unto a wise man.', body: ['The two builders heard the same sermon. Only one did anything about it. The storm was not the test — the foundation was.', 'What you do with what you have heard this week is your foundation for next week.'], prayer: ['Move me from hearer to doer this week.', 'Build my life on what I cannot see when the storm comes.', 'Spare me from the wisdom of admiring sermons I never apply.'], resolve: 'I will obey one thing I have been admiring.', status: 'sent' },
  { d: 17, title: 'Songs in the Night', ref: 'Acts 16:25', verse: 'At midnight Paul and Silas prayed, and sang praises unto God.', body: ['They were beaten, jailed, and uncertain. They sang anyway. The chains did not loosen when their circumstances improved — they loosened when their worship rose.', 'Sing where you are. The earthquake answers the song, not the silence.'], prayer: ['Teach me to worship at midnight, not just at noon.', 'Loose the chains that fall only when I praise.', 'Let my song reach the other prisoners.'], resolve: 'I will sing before the door opens.', status: 'sent' },
  { d: 18, title: 'The Cloak Left Behind', ref: 'Mark 10:50', verse: 'And he, casting away his garment, rose, and came to Jesus.', body: ['Bartimaeus could not see, but he could feel his cloak. It was his identity as a beggar, his collection mat, his proof of need. When Jesus called, he left it.', 'Some of us are trying to follow Jesus while still dragging the cloak that defined our old story.'], prayer: ['Show me the cloak I am still dragging into my new chapter.', 'Give me the courage to leave it where I stood.', 'Let my hands be free for the new thing You are giving.'], resolve: 'I will drop the cloak I no longer need.', status: 'sent' },
  { d: 19, title: 'Bread Broken, Bread Multiplied', ref: 'John 6:11', verse: 'And Jesus took the loaves; and when he had given thanks, he distributed.', body: ['The miracle did not happen in the basket. It happened in the giving. Heaven multiplies what leaves the hand, not what stays in it.', 'Give thanks first. Then give. Then watch.'], prayer: ['Open my hand before I count my loaves.', 'Teach me to give thanks before I see the increase.', 'Multiply what I distribute, not what I hoard.'], resolve: 'I will give thanks, then give, and let God do the math.', status: 'sent', edited: true },
  { d: 20, title: 'When Heaven Is Silent', ref: 'Habakkuk 2:3', verse: 'Though it tarry, wait for it; because it will surely come.', body: ['Silence from heaven is not absence. It is often preparation. Habakkuk was told to write the vision plainly while the answer was still on its way.', 'Write down what God has promised. Read it back to your fear.'], prayer: ['Strengthen me in the waiting season.', 'Help me to write the vision instead of editing the doubt.', 'Sustain my hope against the calendar.'], resolve: 'I will write the vision and outlast the silence.', status: 'sent' },
  { d: 21, title: 'The Hidden Years', ref: 'Luke 2:52', verse: 'And Jesus increased in wisdom and stature, and in favour with God and man.', body: ['Eighteen years of Jesus\' life are summarized in a single verse. The hidden years are not wasted years. They are where favour is grown.', 'Do not despise what is being built in private.'], prayer: ['Help me to value the unseen work.', 'Grow in me what only You can see.', 'Make me trustworthy with hidden assignments.'], resolve: 'I will tend the hidden years with the same care as the public ones.', status: 'sent' },
  { d: 22, title: 'Manna for Today', ref: 'Exodus 16:4', verse: 'The people shall go out and gather a certain rate every day.', body: ['God gave manna daily on purpose. He could have rained down a month\'s worth. He did not. He wanted His people to need Him in the morning.', 'Today\'s grace will not microwave for tomorrow. Come back at sunrise.'], prayer: ['Forgive me for trying to stockpile what You meant to give fresh.', 'Make me a morning person where it counts.', 'Feed me with what I will need only for today.'], resolve: 'I will gather grace fresh every morning.', status: 'sent', edited: true },
  { d: 23, title: 'Sounding the Trumpet', ref: 'Joel 2:1', verse: 'Blow ye the trumpet in Zion, and sound an alarm in my holy mountain.', body: ['Trumpets in scripture were never decorative. They gathered, warned, announced, and crowned. The trumpet of this ministry is not nostalgia — it is a summons.', 'Today, ask God which alarm He is asking you to sound, and to whom. Then sound it without apology.'], prayer: ['Lord, place Your trumpet in mouths that will not be silent.', 'Wake the sleeping ones in my generation.', 'Make me brave enough to be the alarm someone needed.'], resolve: 'I will sound the trumpet entrusted to me, today.', status: 'today' },
  { d: 24, title: 'House of Prayer', ref: 'Isaiah 56:7', verse: 'For mine house shall be called an house of prayer for all people.', body: ['God\'s house is not first a house of programmes. It is a house of prayer. Before we organize, we kneel. Before we strategize, we surrender.', 'Restore prayer as the architecture, not the accessory.'], prayer: ['Make my heart a house of prayer before it is anything else.', 'Forgive us for crowding out intercession with activity.', 'Raise prayer warriors in my generation.'], resolve: 'I will build prayer back into the foundation of my day.', status: 'upcoming' },
  { d: 25, title: 'The Power of a Returning Heart', ref: 'Joel 2:13', verse: 'Rend your heart, and not your garments, and turn unto the LORD your God.', body: ['God is not impressed by torn clothes. He is moved by torn hearts. The returning one does not need the perfect words — just the willingness to face home.', 'You are not too far. You are just one turn away.'], prayer: ['Tear what needs to be torn in me, and spare what You can mend.', 'Receive my return without the speech I prepared.', 'Lead me home one honest step at a time.'], resolve: 'I will turn, and not just appear to turn.', status: 'upcoming' },
  { d: 26, title: 'Friends Who Carry', ref: 'Mark 2:4', verse: 'They uncovered the roof where he was: and they let down the bed wherein the sick of the palsy lay.', body: ['Four friends did not let a crowd between them and a miracle. They climbed. They unroofed. They lowered. Their faith carried someone who could not walk himself.', 'Be that kind of friend. Find that kind of friend.'], prayer: ['Send me four friends, and make me one.', 'Give me the courage to climb roofs for the people I love.', 'Carry through me those who cannot carry themselves today.'], resolve: 'I will be the friend that climbs.', status: 'upcoming' },
  { d: 27, title: 'The Promise in the Plough', ref: 'Luke 9:62', verse: 'No man, having put his hand to the plough, and looking back, is fit for the kingdom of God.', body: ['A plough cuts straight only when the eyes are fixed forward. The kingdom is not for the nostalgic, but for the resolved.', 'Take your hand off the past. Put it on the plough.'], prayer: ['Heal me from glancing back at fields You have already retired.', 'Steady my hands on the plough You have placed before me.', 'Make me fit for the kingdom, not just nostalgic for it.'], resolve: 'I will plough forward, and let yesterday rest.', status: 'upcoming' },
  { d: 28, title: 'The Lord Provides', ref: 'Genesis 22:14', verse: 'And Abraham called the name of that place Jehovah-jireh.', body: ['Provision arrived after Abraham climbed the mountain. The ram was already in the thicket. God\'s supply is often waiting in the place we are afraid to go.', 'Walk to the mountain. The ram is already there.'], prayer: ['Where I have stalled out of fear, send me again.', 'Open my eyes to the ram already in the thicket.', 'Teach me to trust the God who provides on the way, not before.'], resolve: 'I will climb the mountain God has named, and trust Him for the ram.', status: 'upcoming' },
  { d: 29, title: 'A Mantle Falls', ref: '2 Kings 2:13', verse: 'He took up also the mantle of Elijah that fell from him.', body: ['Mantles fall. Generations transition. The question is whether the next one is ready to pick up what God has finished entrusting to the former.', 'Stay close to those God is finishing with. The mantle is going to fall.'], prayer: ['Make me a faithful Elisha to someone\'s Elijah.', 'Prepare me to carry what You are about to drop.', 'Honour the elders You have placed in my path.'], resolve: 'I will stay close, ready to receive what falls.', status: 'upcoming' },
  { d: 30, title: 'The Long View', ref: 'Hebrews 11:13', verse: 'These all died in faith, not having received the promises, but having seen them afar off.', body: ['The cloud of witnesses did not all see the harvest of their faith. Many died planting. Yet none of them counted it as loss, because they had seen it from afar.', 'Live for the long view. Plant trees you may not sit under.'], prayer: ['Lift my eyes from the immediate to the eternal.', 'Help me to plant trees for grandchildren of faith I will not meet.', 'Honour me with seeing from afar what You will fulfil later.'], resolve: 'I will live for what I may not see this side of eternity.', status: 'upcoming' },
  { d: 31, title: 'The Trumpet at Month\'s End', ref: 'Numbers 10:10', verse: 'Also in the day of your gladness, and in your solemn days, ye shall blow with the trumpets.', body: ['The trumpet was sounded in both gladness and solemnity. Whichever May has been for you, sound the trumpet over it. Mark it. Remember it.', 'Do not let a month pass without a trumpet over it.'], prayer: ['Thank You for every day I crossed and every day You carried me through.', 'Seal what was sown, and pardon what was scattered.', 'Sound a trumpet over my next month before I even step into it.'], resolve: 'I will close this month with a trumpet, not a sigh.', status: 'upcoming' },
]

export const SEED_GROUPS: WhatsAppGroup[] = [
  { id: 'g1', name: 'TOTATeens · Main', active: true },
  { id: 'g2', name: 'TOTA · Lagos Cell', active: true },
  { id: 'g3', name: 'TOTA · Abuja Cell', active: true },
  { id: 'g4', name: 'TOTA · Diaspora UK', active: true },
  { id: 'g5', name: 'TOTA · Coordinators', active: true },
  { id: 'g6', name: 'TOTA · Alumni Circle', active: false },
]

export const SEED_HISTORY: HistoryEntry[] = [
  { day: 22, sentAt: 'Fri 22 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 21, sentAt: 'Thu 21 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 20, sentAt: 'Wed 20 May, 02:00', groups: 5, delivered: 4, mode: 'auto', warn: 'TOTA · Diaspora UK delivery delayed' },
  { day: 19, sentAt: 'Tue 19 May, 09:14', groups: 5, delivered: 5, mode: 'manual', note: 'Re-sent after edit' },
  { day: 19, sentAt: 'Tue 19 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 18, sentAt: 'Mon 18 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 17, sentAt: 'Sun 17 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 16, sentAt: 'Sat 16 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 15, sentAt: 'Fri 15 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
  { day: 14, sentAt: 'Thu 14 May, 02:00', groups: 5, delivered: 5, mode: 'auto' },
]

export const SEED_PDF: PdfFile = {
  name: 'TOTA_Devotional_May2026.pdf',
  size: 2.4,
  uploadedAt: '29 Apr 09:12',
}
